/**
 * Data constants for the EmojiPicker component.
 * Curated emoji categories, Lucide icon mappings, and size options.
 * Icons marked `filled: true` render with fill for a solid look.
 */

import {
  Sparkles, Star, Heart, Flower2, Leaf, TreePine, Mountain, Waves,
  Sun, Moon, Cloud, Zap, Coffee, BookOpen, GraduationCap, Palette,
  Music, Camera, Gem, Crown, Feather, Flame, Rocket, Globe, Compass,
  Anchor, Shell, Citrus, Cherry, Clover, Snowflake, Bird, Cat, Dog,
  Fish, Bug, Rabbit, Squirrel, Pencil, PenTool, Brush, Shapes,
  Lightbulb, Target, Trophy, Medal,
  Home, MapPin, Phone, Mail, MessageCircle, Send, Bell, BellRing,
  Bookmark, Flag, Pin, Lock, Unlock, Shield, ShieldCheck,
  Eye, Search, Settings, Wrench, Hammer, CircleDot,
  Square, Triangle, Pentagon, Hexagon, Octagon, Diamond,
  CircleCheck, CircleX, CircleAlert, CircleHelp,
  ThumbsUp, BadgeCheck, Award, Swords,
  Gamepad2, Dice5, Puzzle, Brain,
  Headphones, Mic, Radio, Speaker, Volume2,
  Clapperboard, Film, Tv, Monitor,
  Plane, Car, Ship, Train, Bike,
  Apple, Grape, IceCreamCone, Cake, Pizza, Cookie,
  Baby, PersonStanding, Users, UserCircle,
  Shirt, Glasses, Watch, Umbrella,
  Briefcase, Building2, Landmark, Church, Castle, School,
  Laptop, Smartphone, Tablet, Database, Server, Cpu,
  Code, Terminal, FileCode, GitBranch,
  Infinity, Hash, AtSign, Percent,
  // More icons
  Bolt, CirclePlay, Disc3, Drumstick, Dumbbell, Ear,
  Fingerprint, Gift, HandHeart, HeartHandshake, Key,
  Languages, Layers, LifeBuoy, Link, Magnet, Map,
  Megaphone, MessageSquare, Microscope, Move, Network,
  Newspaper, Package, PaintBucket, Paperclip, PartyPopper,
  PawPrint, PiggyBank, Plug, Power, Presentation, QrCode,
  Receipt, Repeat, Route, Ruler, Scale, Scan, Scissors,
  Share2, ShoppingBag, ShoppingCart, Signpost, Slash,
  Soup, Stethoscope, Store, Sunrise, Sunset, Tag,
  TestTube, Thermometer, Timer, Tornado, TrendingUp,
  Truck, Turtle, Wand2, Wifi, Wine,
  // Even more icons
  Activity, Airplay, AlarmClock, Archive, ArrowUpCircle,
  Banana, Battery, BedDouble, Bluetooth, Bomb, Bone, Box,
  Calendar, CalendarHeart, Candy, CircleArrowUp, CircleDollarSign,
  ClipboardList, CloudRain, CloudSnow, CloudSun, Coins, Contact,
  CreditCard, Croissant, Drama, Droplet, Eclipse, Egg,
  Fan, FileHeart, FileSearch, FishSymbol, Flashlight, FlaskConical,
  Focus, Footprints, Frown, Fuel, Gauge, Ghost, GlassWater,
  GraduationCap as GradCap2, Grid3X3, Grip, Guitar, HandMetal,
  Haze, HeartPulse, Hop, Hospital, Hourglass, Image,
  Inbox, Info, Joystick, Kanban, KeyRound, Lamp,
  Laugh, Layout, Leaf as Leaf2, Library, ListChecks,
  Locate, MapPinned, Martini, Maximize, Minimize,
  Moon as Moon2, Mountain as Mountain2, MousePointer, MoveHorizontal,
  Palette as Palette2, Pause, Pen, Percent as Percent2, PersonStanding as PersonStanding2,
  PieChart, Pill, PlaneLanding, PlaneTakeoff, PlayCircle,
  Pocket, Popcorn, Printer, Radio as Radio2, Rainbow,
  Refrigerator, Rocket as Rocket2, RotateCcw, Salad, Sandwich,
  Save, ScrollText, Search as Search2, Shield as Shield2,
  SlidersHorizontal, Smile, SmilePlus, Snail, Sparkle,
  SpeakerIcon, Sprout, SquareStack, Stamp, StarHalf,
  Subscript, Superscript, SwissFranc, Syringe, Tent,
  ToggleLeft, Torus, TreeDeciduous, Unplug, Upload,
  Utensils, Vault, Vibrate, Video, Voicemail, Wallet,
  Waypoints, Webcam, WholeWord, Wind, Workflow,
  type LucideIcon,
} from "lucide-react";

/** Icon size options for board icons. */
export const ICON_SIZES: { label: string; value: string; px: number }[] = [
  { label: "S", value: "sm", px: 48 },
  { label: "M", value: "md", px: 80 },
  { label: "L", value: "lg", px: 112 },
  { label: "XL", value: "xl", px: 144 },
];

/** Entry for a Lucide icon with optional filled rendering. */
export interface LucideIconEntry {
  name: string;
  icon: LucideIcon;
  filled?: boolean;
}

/** Lucide icon name to component mapping for rendering stored icons. */
export const LUCIDE_ICON_MAP: Record<string, LucideIcon> = {
  sparkles: Sparkles, star: Star, heart: Heart, flower2: Flower2,
  leaf: Leaf, "tree-pine": TreePine, mountain: Mountain, waves: Waves,
  sun: Sun, moon: Moon, cloud: Cloud, zap: Zap, coffee: Coffee,
  "book-open": BookOpen, "graduation-cap": GraduationCap, palette: Palette,
  music: Music, camera: Camera, gem: Gem, crown: Crown, feather: Feather,
  flame: Flame, rocket: Rocket, globe: Globe, compass: Compass,
  anchor: Anchor, shell: Shell, citrus: Citrus, cherry: Cherry,
  clover: Clover, snowflake: Snowflake, bird: Bird, cat: Cat, dog: Dog,
  fish: Fish, bug: Bug, rabbit: Rabbit, squirrel: Squirrel, pencil: Pencil,
  "pen-tool": PenTool, brush: Brush, shapes: Shapes, lightbulb: Lightbulb,
  target: Target, trophy: Trophy, medal: Medal,
  home: Home, "map-pin": MapPin, phone: Phone, mail: Mail,
  "message-circle": MessageCircle, send: Send, bell: Bell, "bell-ring": BellRing,
  bookmark: Bookmark, flag: Flag, pin: Pin, lock: Lock, unlock: Unlock,
  shield: Shield, "shield-check": ShieldCheck, eye: Eye, search: Search,
  settings: Settings, wrench: Wrench, hammer: Hammer, "circle-dot": CircleDot,
  square: Square, triangle: Triangle, pentagon: Pentagon, hexagon: Hexagon,
  octagon: Octagon, diamond: Diamond,
  "circle-check": CircleCheck, "circle-x": CircleX,
  "circle-alert": CircleAlert, "circle-help": CircleHelp,
  "thumbs-up": ThumbsUp, "badge-check": BadgeCheck, award: Award, swords: Swords,
  gamepad2: Gamepad2, dice5: Dice5, puzzle: Puzzle, brain: Brain,
  headphones: Headphones, mic: Mic, radio: Radio, speaker: Speaker, volume2: Volume2,
  clapperboard: Clapperboard, film: Film, tv: Tv, monitor: Monitor,
  plane: Plane, car: Car, ship: Ship, train: Train, bike: Bike,
  apple: Apple, grape: Grape, "ice-cream-cone": IceCreamCone, cake: Cake,
  pizza: Pizza, cookie: Cookie,
  baby: Baby, "person-standing": PersonStanding, users: Users, "user-circle": UserCircle,
  shirt: Shirt, glasses: Glasses, watch: Watch, umbrella: Umbrella,
  briefcase: Briefcase, building2: Building2, landmark: Landmark, church: Church,
  castle: Castle, school: School,
  laptop: Laptop, smartphone: Smartphone, tablet: Tablet, database: Database,
  server: Server, cpu: Cpu,
  code: Code, terminal: Terminal, "file-code": FileCode, "git-branch": GitBranch,
  infinity: Infinity, hash: Hash, "at-sign": AtSign, percent: Percent,
  bolt: Bolt, "circle-play": CirclePlay, disc3: Disc3, drumstick: Drumstick,
  dumbbell: Dumbbell, ear: Ear, fingerprint: Fingerprint, gift: Gift,
  "hand-heart": HandHeart, "heart-handshake": HeartHandshake, key: Key,
  languages: Languages, layers: Layers, "life-buoy": LifeBuoy, link: Link,
  magnet: Magnet, map: Map, megaphone: Megaphone, "message-square": MessageSquare,
  microscope: Microscope, move: Move, network: Network, newspaper: Newspaper,
  package: Package, "paint-bucket": PaintBucket, paperclip: Paperclip,
  "party-popper": PartyPopper, "paw-print": PawPrint, "piggy-bank": PiggyBank,
  plug: Plug, power: Power, presentation: Presentation, "qr-code": QrCode,
  receipt: Receipt, repeat: Repeat, route: Route, ruler: Ruler, scale: Scale,
  scan: Scan, scissors: Scissors, share2: Share2, "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart, signpost: Signpost, slash: Slash, soup: Soup,
  stethoscope: Stethoscope, store: Store, sunrise: Sunrise, sunset: Sunset,
  tag: Tag, "test-tube": TestTube, thermometer: Thermometer, timer: Timer,
  tornado: Tornado, "trending-up": TrendingUp, truck: Truck, turtle: Turtle,
  wand2: Wand2, wifi: Wifi, wine: Wine,
};

// Lazy-built set of filled icon names
let _filledSet: Set<string> | null = null;

/**
 * Returns whether a stored icon name should render filled.
 *
 * @param name - Lucide icon name (without "lucide:" prefix)
 * @returns true if the icon should use fill="currentColor"
 */
export function isFilledIcon(name: string): boolean {
  if (!_filledSet) {
    _filledSet = new Set<string>();
    for (const cat of LUCIDE_CATEGORIES) {
      for (const icon of cat.icons) {
        if (icon.filled) _filledSet.add(icon.name);
      }
    }
  }
  return _filledSet.has(name);
}

/** Comprehensive emoji categories — all standard Unicode emojis. */
export const EMOJI_CATEGORIES: { label: string; emojis: string[] }[] = [
  {
    label: "Smileys",
    emojis: [
      "😀", "😃", "😄", "😁", "😆", "😅", "🤣", "😂", "🙂", "🙃",
      "🫠", "😉", "😊", "😇", "🥰", "😍", "🤩", "😘", "😗", "☺️",
      "😚", "😙", "🥲", "😋", "😛", "😜", "🤪", "😝", "🤑", "🤗",
      "🤭", "🫢", "🫣", "🤫", "🤔", "🫡", "🤐", "🤨", "😐", "😑",
      "😶", "🫥", "😏", "😒", "🙄", "😬", "🤥", "🫨", "😌", "😔",
      "😪", "🤤", "😴", "😷", "🤒", "🤕", "🤢", "🤮", "🥴", "😵",
      "😵‍💫", "🤯", "🤠", "🥳", "🥸", "😎", "🤓", "🧐", "😕", "🫤",
      "😟", "🙁", "☹️", "😮", "😯", "😲", "😳", "🥺", "🥹", "😦",
      "😧", "😨", "😰", "😥", "😢", "😭", "😱", "😖", "😣", "😞",
      "😓", "😩", "😫", "🥱", "😤", "😡", "😠", "🤬", "😈", "👿",
      "💀", "☠️", "💩", "🤡", "👹", "👺", "👻", "👽", "👾", "🤖",
    ],
  },
  {
    label: "Gestures & People",
    emojis: [
      "👋", "🤚", "🖐️", "✋", "🖖", "🫱", "🫲", "🫳", "🫴", "🫷",
      "🫸", "👌", "🤌", "🤏", "✌️", "🤞", "🫰", "🤟", "🤘", "🤙",
      "👈", "👉", "👆", "🖕", "👇", "☝️", "🫵", "👍", "👎", "✊",
      "👊", "🤛", "🤜", "👏", "🙌", "🫶", "👐", "🤲", "🤝", "🙏",
      "✍️", "💅", "🤳", "💪", "🦾", "🦿", "🦵", "🦶", "👂", "🦻",
      "👃", "👶", "🧒", "👦", "👧", "🧑", "👱", "👨", "🧔", "👩",
      "🧓", "👴", "👵", "🙍", "🙎", "🙅", "🙆", "💁", "🙋", "🧏",
      "🙇", "🤦", "🤷", "👮", "🕵️", "💂", "🥷", "👷", "🫅", "🤴",
      "👸", "👳", "👲", "🧕", "🤵", "👰", "🤰", "🫃", "🫄", "🤱",
      "👼", "🎅", "🤶", "🦸", "🦹", "🧙", "🧚", "🧛", "🧜", "🧝",
      "🧞", "🧟", "🧌", "💆", "💇", "🚶", "🧍", "🧎", "🏃", "💃",
      "🕺", "🕴️", "👯", "🧖", "🧗", "🤸", "⛹️", "🏋️", "🚴", "🚵",
    ],
  },
  {
    label: "Hearts & Emotions",
    emojis: [
      "❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "❤️‍🔥",
      "❤️‍🩹", "💔", "❣️", "💕", "💞", "💓", "💗", "💖", "💘", "💝",
      "💟", "♥️", "🩷", "🩵", "🩶", "💋", "💌", "💐", "🌹", "😻",
      "💑", "👩‍❤️‍👨", "👨‍❤️‍👨", "👩‍❤️‍👩", "💏", "👪", "👨‍👩‍👦", "👨‍👩‍👧",
      "💤", "💢", "💬", "👁️‍🗨️", "🗨️", "🗯️", "💭", "💮", "🏵️", "🎀",
    ],
  },
  {
    label: "Animals",
    emojis: [
      "🐶", "🐕", "🦮", "🐕‍🦺", "🐩", "🐺", "🦊", "🦝", "🐱", "🐈",
      "🐈‍⬛", "🦁", "🐯", "🐅", "🐆", "🐴", "🫎", "🫏", "🦄", "🦓",
      "🦌", "🦬", "🐮", "🐂", "🐃", "🐄", "🐷", "🐖", "🐗", "🐽",
      "🐏", "🐑", "🐐", "🐪", "🐫", "🦙", "🦒", "🐘", "🦣", "🦏",
      "🦛", "🐭", "🐁", "🐀", "🐹", "🐰", "🐇", "🐿️", "🦫", "🦔",
      "🦇", "🐻", "🐻‍❄️", "🐨", "🐼", "🦥", "🦦", "🦨", "🦘", "🦡",
      "🐾", "🦃", "🐔", "🐓", "🐣", "🐤", "🐥", "🐦", "🐧", "🕊️",
      "🦅", "🦆", "🦢", "🦉", "🦤", "🪶", "🦩", "🦚", "🦜", "🪽",
      "🐦‍⬛", "🪿", "🐸", "🐊", "🐢", "🦎", "🐍", "🐲", "🐉", "🦕",
      "🦖", "🐳", "🐋", "🐬", "🦭", "🐟", "🐠", "🐡", "🦈", "🐙",
      "🐚", "🪸", "🪼", "🐌", "🦋", "🐛", "🐜", "🐝", "🪲", "🐞",
      "🦗", "🪳", "🕷️", "🕸️", "🦂", "🦟", "🪰", "🪱", "🦠", "🐾",
    ],
  },
  {
    label: "Plants & Flowers",
    emojis: [
      "💐", "🌸", "💮", "🪷", "🏵️", "🌹", "🥀", "🌺", "🌻", "🌼",
      "🌷", "🪻", "🌱", "🪴", "🌲", "🌳", "🌴", "🌵", "🌾", "🌿",
      "☘️", "🍀", "🍁", "🍂", "🍃", "🪹", "🪺", "🍄", "🍄‍🟫", "🌰",
      "🪵", "🪨", "🫧", "🌊", "🌋", "🏔️", "⛰️", "🏜️", "🏝️", "🏞️",
    ],
  },
  {
    label: "Weather & Sky",
    emojis: [
      "☀️", "🌤️", "⛅", "🌥️", "☁️", "🌦️", "🌧️", "⛈️", "🌩️", "🌨️",
      "❄️", "☃️", "⛄", "🌬️", "💨", "🌪️", "🌫️", "🌈", "☔", "💧",
      "💦", "🌊", "⚡", "🔥", "✨", "⭐", "🌟", "💫", "🌙", "🌛",
      "🌜", "🌚", "🌝", "🌞", "🪐", "🌍", "🌎", "🌏", "🌑", "🌒",
      "🌓", "🌔", "🌕", "🌖", "🌗", "🌘", "☄️", "🌌", "🌠", "🌃",
    ],
  },
  {
    label: "Food & Drink",
    emojis: [
      "🍇", "🍈", "🍉", "🍊", "🍋", "🍋‍🟩", "🍌", "🍍", "🥭", "🍎",
      "🍏", "🍐", "🍑", "🍒", "🍓", "🫐", "🥝", "🍅", "🫒", "🥥",
      "🥑", "🍆", "🥔", "🥕", "🌽", "🌶️", "🫑", "🥒", "🥬", "🥦",
      "🧄", "🧅", "🥜", "🫘", "🌰", "🫚", "🫛", "🍞", "🥐", "🥖",
      "🫓", "🥨", "🥯", "🥞", "🧇", "🧀", "🍖", "🍗", "🥩", "🥓",
      "🍔", "🍟", "🍕", "🌭", "🥪", "🌮", "🌯", "🫔", "🥙", "🧆",
      "🥚", "🍳", "🥘", "🍲", "🫕", "🥣", "🥗", "🍿", "🧈", "🧂",
      "🥫", "🍱", "🍘", "🍙", "🍚", "🍛", "🍜", "🍝", "🍠", "🍢",
      "🍣", "🍤", "🍥", "🥮", "🍡", "🥟", "🥠", "🥡", "🦀", "🦞",
      "🦐", "🦑", "🦪", "🍦", "🍧", "🍨", "🍩", "🍪", "🎂", "🍰",
      "🧁", "🥧", "🍫", "🍬", "🍭", "🍮", "🍯", "🍼", "🥛", "☕",
      "🫖", "🍵", "🍶", "🍾", "🍷", "🍸", "🍹", "🍺", "🍻", "🥂",
      "🥃", "🫗", "🥤", "🧋", "🧃", "🧉", "🧊", "🥢", "🍽️", "🍴",
      "🥄", "🔪", "🫙", "🏺",
    ],
  },
  {
    label: "Activities & Sports",
    emojis: [
      "⚽", "🏀", "🏈", "⚾", "🥎", "🎾", "🏐", "🏉", "🥏", "🎱",
      "🪀", "🏓", "🏸", "🏒", "🏑", "🥍", "🏏", "🪃", "🥅", "⛳",
      "🪁", "🏹", "🎣", "🤿", "🥊", "🥋", "🎽", "🛹", "🛼", "🛷",
      "⛸️", "🥌", "🎿", "⛷️", "🏂", "🪂", "🏋️", "🤼", "🤸", "⛹️",
      "🤺", "🤾", "🏌️", "🏇", "🧘", "🏄", "🏊", "🤽", "🚣", "🧗",
      "🚵", "🚴", "🏆", "🥇", "🥈", "🥉", "🏅", "🎖️", "🏵️", "🎗️",
      "🎪", "🤹", "🎭", "🩰", "🎨", "🎬", "🎤", "🎧", "🎼", "🎹",
      "🥁", "🪘", "🪗", "🎷", "🎺", "🪈", "🎸", "🪕", "🎻", "🪇",
      "🎲", "♟️", "🎯", "🎳", "🎮", "🕹️", "🎰", "🧩", "🪄", "🎈",
      "🎉", "🎊", "🎀", "🎁", "🎆", "🎇", "🧨", "✨", "🪅", "🪩",
      "🪆", "🎑", "🎐", "🏮", "🪔", "🧧",
    ],
  },
  {
    label: "Travel & Places",
    emojis: [
      "🚗", "🚕", "🚙", "🚌", "🚎", "🏎️", "🚓", "🚑", "🚒", "🚐",
      "🛻", "🚚", "🚛", "🚜", "🏍️", "🛵", "🛺", "🚲", "🛴", "🛹",
      "🛼", "🚏", "🛣️", "🛤️", "⛽", "🛞", "🚨", "🚥", "🚦", "🚧",
      "⚓", "🛟", "⛵", "🛶", "🚤", "🛳️", "⛴️", "🛥️", "🚢", "✈️",
      "🛩️", "🛫", "🛬", "🪂", "💺", "🚁", "🚟", "🚠", "🚡", "🛰️",
      "🚀", "🛸", "🛎️", "🧳", "⏰", "⌛", "⏳", "🕐", "🕑", "🕒",
      "🏠", "🏡", "🏘️", "🏚️", "🏗️", "🏢", "🏣", "🏤", "🏥", "🏦",
      "🏨", "🏩", "🏪", "🏫", "🏬", "🏭", "🏯", "🏰", "💒", "🗼",
      "🗽", "⛪", "🕌", "🛕", "🕍", "⛩️", "🕋", "⛲", "⛺", "🌁",
      "🌃", "🏙️", "🌄", "🌅", "🌆", "🌇", "🌉", "🗾", "🏔️", "⛰️",
      "🌋", "🗻", "🏕️", "🏖️", "🏜️", "🏝️", "🏞️", "🗺️", "🧭", "🌐",
    ],
  },
  {
    label: "Objects",
    emojis: [
      "⌚", "📱", "📲", "💻", "⌨️", "🖥️", "🖨️", "🖱️", "🖲️", "🕹️",
      "🗜️", "💽", "💾", "💿", "📀", "📼", "📷", "📸", "📹", "🎥",
      "📽️", "🎞️", "📞", "☎️", "📟", "📠", "📺", "📻", "🎙️", "🎚️",
      "🎛️", "🧭", "⏱️", "⏲️", "⏰", "🕰️", "⌛", "⏳", "📡", "🔋",
      "🪫", "🔌", "💡", "🔦", "🕯️", "🪔", "🧯", "🛢️", "💸", "💵",
      "💴", "💶", "💷", "🪙", "💰", "💳", "💎", "⚖️", "🪜", "🧰",
      "🪛", "🔧", "🔨", "⚒️", "🛠️", "⛏️", "🪚", "🔩", "⚙️", "🪤",
      "🧱", "⛓️", "🧲", "🔫", "💣", "🧨", "🪓", "🔪", "🗡️", "⚔️",
      "🛡️", "🚬", "⚰️", "🪦", "⚱️", "🏺", "🔮", "📿", "🧿", "🪬",
      "💈", "⚗️", "🔭", "🔬", "🕳️", "🩹", "🩺", "🩻", "🩼", "💊",
      "💉", "🩸", "🧬", "🦠", "🧫", "🧪", "🌡️", "🧹", "🪠", "🧺",
      "🧻", "🚽", "🚰", "🚿", "🛁", "🛀", "🧼", "🪥", "🪒", "🧽",
      "🪣", "🧴", "🛎️", "🔑", "🗝️", "🚪", "🪑", "🛋️", "🛏️", "🛌",
      "🧸", "🪆", "🖼️", "🪞", "🪟", "🛍️", "🛒", "🎁", "🎈", "🎏",
      "🎀", "🪄", "🪅", "🎊", "🎉", "🎎", "🏮", "🎐", "🧧", "✉️",
      "📩", "📨", "📧", "💌", "📥", "📤", "📦", "🏷️", "🪧",
    ],
  },
  {
    label: "Books & Writing",
    emojis: [
      "📮", "📪", "📫", "📬", "📭", "📜", "📃", "📄", "📑", "🧾",
      "📊", "📈", "📉", "🗒️", "🗓️", "📆", "📅", "🗑️", "📇", "🗃️",
      "🗳️", "🗄️", "📋", "📁", "📂", "🗂️", "🗞️", "📰", "📓", "📔",
      "📒", "📕", "📗", "📘", "📙", "📚", "📖", "🔖", "🧷", "🔗",
      "📎", "🖇️", "📐", "📏", "🧮", "📌", "📍", "✂️", "🖊️", "🖋️",
      "✒️", "🖌️", "🖍️", "📝", "✏️", "🔍", "🔎", "🔏", "🔐", "🔒",
      "🔓",
    ],
  },
  {
    label: "Symbols",
    emojis: [
      "❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "🩷",
      "🩵", "🩶", "💯", "💢", "💥", "💫", "💦", "💨", "🕳️", "💬",
      "🗨️", "🗯️", "💭", "🔔", "🔕", "🎵", "🎶", "🏧", "🚮", "🚰",
      "♿", "🚹", "🚺", "🚻", "🚼", "🚾", "⚠️", "🚸", "⛔", "🚫",
      "🚳", "🚭", "🚯", "🚱", "🚷", "📵", "🔞", "☢️", "☣️", "⬆️",
      "↗️", "➡️", "↘️", "⬇️", "↙️", "⬅️", "↖️", "↕️", "↔️", "↩️",
      "↪️", "⤴️", "⤵️", "🔃", "🔄", "🔙", "🔚", "🔛", "🔜", "🔝",
      "☮️", "✡️", "☸️", "🪯", "✝️", "☦️", "☪️", "☯️", "🕉️", "⚛️",
      "♾️", "🔯", "✴️", "🆔", "⚜️", "🔰", "♻️", "✅", "☑️", "✔️",
      "❌", "❎", "➕", "➖", "➗", "✖️", "💲", "💱", "©️", "®️",
      "™️", "🔴", "🟠", "🟡", "🟢", "🔵", "🟣", "⚫", "⚪", "🟤",
      "🔺", "🔻", "🔸", "🔹", "🔶", "🔷", "🔘", "🔲", "🔳", "⬛",
      "⬜", "◼️", "◻️", "◾", "◽", "▪️", "▫️", "🟥", "🟧", "🟨",
      "🟩", "🟦", "🟪", "🟫", "⭕", "❗", "❓", "❕", "❔", "‼️",
      "⁉️", "🏁", "🚩", "🎌", "🏴", "🏳️", "🏳️‍🌈", "🏳️‍⚧️", "🏴‍☠️",
    ],
  },
  {
    label: "Flags",
    emojis: [
      "🇺🇸", "🇬🇧", "🇨🇦", "🇦🇺", "🇫🇷", "🇩🇪", "🇮🇹", "🇪🇸", "🇯🇵", "🇰🇷",
      "🇨🇳", "🇮🇳", "🇧🇷", "🇲🇽", "🇷🇺", "🇿🇦", "🇳🇬", "🇪🇬", "🇹🇷", "🇸🇦",
      "🇦🇪", "🇮🇱", "🇹🇭", "🇻🇳", "🇵🇭", "🇮🇩", "🇲🇾", "🇸🇬", "🇳🇿", "🇦🇷",
      "🇨🇴", "🇨🇱", "🇵🇪", "🇪🇨", "🇨🇺", "🇯🇲", "🇵🇷", "🇳🇴", "🇸🇪", "🇫🇮",
      "🇩🇰", "🇮🇸", "🇮🇪", "🇵🇹", "🇬🇷", "🇵🇱", "🇨🇿", "🇦🇹", "🇨🇭", "🇧🇪",
      "🇳🇱", "🇺🇦", "🇷🇴", "🇭🇺", "🇭🇷", "🇷🇸", "🇧🇬", "🇱🇹", "🇱🇻", "🇪🇪",
      "🇵🇰", "🇧🇩", "🇱🇰", "🇳🇵", "🇲🇲", "🇰🇭", "🇱🇦", "🇲🇳", "🇰🇿", "🇺🇿",
      "🇰🇪", "🇪🇹", "🇬🇭", "🇹🇿", "🇨🇲", "🇨🇮", "🇲🇦", "🇹🇳", "🇩🇿", "🇱🇾",
      "🇶🇦", "🇰🇼", "🇧🇭", "🇴🇲", "🇯🇴", "🇱🇧", "🇮🇶", "🇮🇷", "🇦🇫", "🇵🇸",
      "🇹🇼", "🇭🇰", "🇲🇴",
    ],
  },
];

/** Lucide icon categories for the Icons tab. */
export const LUCIDE_CATEGORIES: {
  label: string;
  icons: LucideIconEntry[];
}[] = [
  {
    label: "Favorites",
    icons: [
      { name: "heart", icon: Heart, filled: true },
      { name: "star", icon: Star, filled: true },
      { name: "bookmark", icon: Bookmark, filled: true },
      { name: "flag", icon: Flag, filled: true },
      { name: "circle-check", icon: CircleCheck, filled: true },
      { name: "badge-check", icon: BadgeCheck, filled: true },
      { name: "thumbs-up", icon: ThumbsUp, filled: true },
      { name: "bell", icon: Bell, filled: true },
      { name: "pin", icon: Pin, filled: true },
    ],
  },
  {
    label: "Shapes",
    icons: [
      { name: "circle-dot", icon: CircleDot, filled: true },
      { name: "square", icon: Square, filled: true },
      { name: "triangle", icon: Triangle, filled: true },
      { name: "diamond", icon: Diamond, filled: true },
      { name: "pentagon", icon: Pentagon, filled: true },
      { name: "hexagon", icon: Hexagon, filled: true },
      { name: "octagon", icon: Octagon, filled: true },
      { name: "shapes", icon: Shapes, filled: true },
      { name: "layers", icon: Layers },
    ],
  },
  {
    label: "Aesthetic",
    icons: [
      { name: "sparkles", icon: Sparkles },
      { name: "gem", icon: Gem, filled: true },
      { name: "crown", icon: Crown, filled: true },
      { name: "feather", icon: Feather },
      { name: "flame", icon: Flame, filled: true },
      { name: "zap", icon: Zap, filled: true },
      { name: "bolt", icon: Bolt, filled: true },
      { name: "infinity", icon: Infinity },
      { name: "shield", icon: Shield, filled: true },
      { name: "wand2", icon: Wand2 },
      { name: "fingerprint", icon: Fingerprint },
      { name: "key", icon: Key, filled: true },
      { name: "magnet", icon: Magnet },
      { name: "power", icon: Power },
      { name: "tornado", icon: Tornado },
      { name: "gift", icon: Gift, filled: true },
      { name: "party-popper", icon: PartyPopper },
      { name: "hand-heart", icon: HandHeart },
    ],
  },
  {
    label: "Nature",
    icons: [
      { name: "flower2", icon: Flower2 },
      { name: "leaf", icon: Leaf, filled: true },
      { name: "tree-pine", icon: TreePine, filled: true },
      { name: "clover", icon: Clover },
      { name: "mountain", icon: Mountain, filled: true },
      { name: "waves", icon: Waves },
      { name: "sun", icon: Sun },
      { name: "moon", icon: Moon, filled: true },
      { name: "cloud", icon: Cloud, filled: true },
      { name: "snowflake", icon: Snowflake },
      { name: "sunrise", icon: Sunrise },
      { name: "sunset", icon: Sunset },
      { name: "thermometer", icon: Thermometer },
      { name: "citrus", icon: Citrus },
      { name: "cherry", icon: Cherry },
      { name: "apple", icon: Apple, filled: true },
      { name: "grape", icon: Grape },
      { name: "turtle", icon: Turtle },
    ],
  },
  {
    label: "Animals",
    icons: [
      { name: "bird", icon: Bird },
      { name: "cat", icon: Cat },
      { name: "dog", icon: Dog },
      { name: "fish", icon: Fish },
      { name: "bug", icon: Bug },
      { name: "rabbit", icon: Rabbit },
      { name: "squirrel", icon: Squirrel },
      { name: "shell", icon: Shell },
      { name: "paw-print", icon: PawPrint },
    ],
  },
  {
    label: "Creative",
    icons: [
      { name: "palette", icon: Palette },
      { name: "music", icon: Music },
      { name: "headphones", icon: Headphones, filled: true },
      { name: "mic", icon: Mic, filled: true },
      { name: "camera", icon: Camera, filled: true },
      { name: "clapperboard", icon: Clapperboard },
      { name: "film", icon: Film },
      { name: "disc3", icon: Disc3 },
      { name: "pencil", icon: Pencil },
      { name: "brush", icon: Brush },
      { name: "pen-tool", icon: PenTool },
      { name: "paint-bucket", icon: PaintBucket },
      { name: "lightbulb", icon: Lightbulb, filled: true },
      { name: "brain", icon: Brain },
      { name: "scissors", icon: Scissors },
      { name: "ruler", icon: Ruler },
      { name: "megaphone", icon: Megaphone, filled: true },
      { name: "newspaper", icon: Newspaper },
    ],
  },
  {
    label: "Work & School",
    icons: [
      { name: "briefcase", icon: Briefcase, filled: true },
      { name: "graduation-cap", icon: GraduationCap, filled: true },
      { name: "book-open", icon: BookOpen },
      { name: "school", icon: School },
      { name: "trophy", icon: Trophy, filled: true },
      { name: "medal", icon: Medal },
      { name: "award", icon: Award },
      { name: "target", icon: Target },
      { name: "coffee", icon: Coffee, filled: true },
      { name: "laptop", icon: Laptop },
      { name: "smartphone", icon: Smartphone },
      { name: "presentation", icon: Presentation },
      { name: "receipt", icon: Receipt },
      { name: "piggy-bank", icon: PiggyBank },
      { name: "scale", icon: Scale },
      { name: "microscope", icon: Microscope },
      { name: "test-tube", icon: TestTube },
      { name: "stethoscope", icon: Stethoscope },
    ],
  },
  {
    label: "Communication",
    icons: [
      { name: "mail", icon: Mail, filled: true },
      { name: "message-circle", icon: MessageCircle, filled: true },
      { name: "message-square", icon: MessageSquare, filled: true },
      { name: "send", icon: Send, filled: true },
      { name: "phone", icon: Phone, filled: true },
      { name: "bell-ring", icon: BellRing },
      { name: "eye", icon: Eye },
      { name: "users", icon: Users },
      { name: "user-circle", icon: UserCircle },
      { name: "languages", icon: Languages },
      { name: "share2", icon: Share2 },
      { name: "link", icon: Link },
      { name: "qr-code", icon: QrCode },
      { name: "wifi", icon: Wifi },
      { name: "network", icon: Network },
      { name: "scan", icon: Scan },
      { name: "paperclip", icon: Paperclip },
      { name: "tag", icon: Tag, filled: true },
    ],
  },
  {
    label: "Travel & Places",
    icons: [
      { name: "home", icon: Home, filled: true },
      { name: "map-pin", icon: MapPin, filled: true },
      { name: "globe", icon: Globe },
      { name: "compass", icon: Compass },
      { name: "map", icon: Map },
      { name: "plane", icon: Plane, filled: true },
      { name: "car", icon: Car },
      { name: "rocket", icon: Rocket, filled: true },
      { name: "anchor", icon: Anchor },
      { name: "building2", icon: Building2 },
      { name: "landmark", icon: Landmark },
      { name: "store", icon: Store },
      { name: "route", icon: Route },
      { name: "signpost", icon: Signpost },
      { name: "truck", icon: Truck },
      { name: "ship", icon: Ship },
      { name: "train", icon: Train },
      { name: "bike", icon: Bike },
    ],
  },
  {
    label: "Food & Drink",
    icons: [
      { name: "pizza", icon: Pizza },
      { name: "cake", icon: Cake },
      { name: "cookie", icon: Cookie },
      { name: "ice-cream-cone", icon: IceCreamCone },
      { name: "soup", icon: Soup },
      { name: "drumstick", icon: Drumstick },
      { name: "wine", icon: Wine },
      { name: "coffee", icon: Coffee },
      { name: "apple", icon: Apple },
    ],
  },
  {
    label: "Gaming & Fun",
    icons: [
      { name: "gamepad2", icon: Gamepad2 },
      { name: "dice5", icon: Dice5 },
      { name: "puzzle", icon: Puzzle },
      { name: "swords", icon: Swords },
      { name: "tv", icon: Tv },
      { name: "radio", icon: Radio },
      { name: "circle-play", icon: CirclePlay, filled: true },
      { name: "dumbbell", icon: Dumbbell },
      { name: "timer", icon: Timer },
    ],
  },
  {
    label: "Developer",
    icons: [
      { name: "code", icon: Code },
      { name: "terminal", icon: Terminal, filled: true },
      { name: "file-code", icon: FileCode },
      { name: "git-branch", icon: GitBranch },
      { name: "cpu", icon: Cpu },
      { name: "server", icon: Server },
      { name: "database", icon: Database },
      { name: "hash", icon: Hash },
      { name: "at-sign", icon: AtSign },
    ],
  },
  {
    label: "Objects",
    icons: [
      { name: "shirt", icon: Shirt },
      { name: "glasses", icon: Glasses },
      { name: "watch", icon: Watch },
      { name: "umbrella", icon: Umbrella },
      { name: "shopping-bag", icon: ShoppingBag, filled: true },
      { name: "shopping-cart", icon: ShoppingCart },
      { name: "package", icon: Package },
      { name: "plug", icon: Plug },
      { name: "life-buoy", icon: LifeBuoy },
    ],
  },
];
