/**
 * Comprehensive list of U.S. four-year colleges + a handful of well-known
 * international schools. Pulled together from the IPEDS accredited-institution
 * registry, U.S. News rankings, and the major HBCU/religious/specialty lists.
 *
 * Any school not in this list can still be entered as free-form text via the
 * "Other" path in SearchableSelect, so missing names aren't blocking.
 */
export const SCHOOL_OPTIONS: string[] = [
  // ---- University of California ----
  "UC Berkeley",
  "UCLA",
  "UC San Diego",
  "UC Davis",
  "UC Irvine",
  "UC Santa Barbara",
  "UC Santa Cruz",
  "UC Riverside",
  "UC Merced",
  "UCSF",
  // ---- California State + Cal Poly ----
  "Cal Poly San Luis Obispo",
  "Cal Poly Pomona",
  "Cal Poly Humboldt",
  "San Diego State",
  "San Jose State",
  "San Francisco State",
  "CSU Long Beach",
  "CSU Fullerton",
  "CSU Northridge",
  "CSU Los Angeles",
  "CSU East Bay",
  "CSU Sacramento",
  "CSU Fresno",
  "CSU Chico",
  "CSU Bakersfield",
  "CSU Channel Islands",
  "CSU Dominguez Hills",
  "CSU Monterey Bay",
  "CSU San Bernardino",
  "CSU San Marcos",
  "CSU Stanislaus",
  "Sonoma State",
  // ---- Ivy League ----
  "Harvard",
  "Yale",
  "Princeton",
  "Columbia",
  "Cornell",
  "UPenn",
  "Brown",
  "Dartmouth",
  // ---- Top private R1 ----
  "Stanford",
  "MIT",
  "Caltech",
  "Carnegie Mellon",
  "Johns Hopkins",
  "Washington University in St. Louis",
  "Northwestern",
  "University of Chicago",
  "Duke",
  "Vanderbilt",
  "Emory",
  "Rice",
  "Notre Dame",
  "Georgetown",
  "USC",
  "NYU",
  "Boston University",
  "Boston College",
  "Northeastern",
  "Tufts",
  "Wake Forest",
  "Tulane",
  "Case Western Reserve",
  "Brandeis",
  "Lehigh",
  "Stevens Institute of Technology",
  "Rensselaer Polytechnic Institute (RPI)",
  "Worcester Polytechnic Institute (WPI)",
  "Drexel",
  "Fordham",
  "Pepperdine",
  "Santa Clara University",
  "University of San Diego",
  "University of San Francisco",
  "Loyola Marymount",
  "Loyola University Chicago",
  "Loyola University Maryland",
  "Loyola University New Orleans",
  "Saint Louis University",
  "Marquette",
  "DePaul",
  "Creighton",
  "Gonzaga",
  "Seattle University",
  "Saint Mary's College of California",
  "American University",
  "George Washington University",
  "Catholic University of America",
  "Howard University",
  "Syracuse",
  "University of Rochester",
  "University of Miami",
  "Southern Methodist University (SMU)",
  "TCU",
  "Baylor",
  "Yeshiva University",
  "Hofstra",
  "Adelphi",
  "Long Island University",
  "Pace University",
  "New School",
  "Pratt Institute",
  "Parsons School of Design",
  "Cooper Union",
  "Rhode Island School of Design (RISD)",
  "School of the Art Institute of Chicago (SAIC)",
  "Berklee College of Music",
  "Juilliard",
  "Manhattan School of Music",
  "Massachusetts College of Art",
  "California Institute of the Arts (CalArts)",
  "Otis College of Art and Design",
  "Art Center College of Design",
  "Savannah College of Art and Design (SCAD)",
  // ---- Liberal Arts Colleges ----
  "Williams",
  "Amherst",
  "Pomona",
  "Swarthmore",
  "Wellesley",
  "Bowdoin",
  "Middlebury",
  "Claremont McKenna",
  "Harvey Mudd",
  "Carleton",
  "Davidson",
  "Smith",
  "Vassar",
  "Haverford",
  "Hamilton",
  "Wesleyan",
  "Colby",
  "Bates",
  "Colgate",
  "Bucknell",
  "Macalester",
  "Grinnell",
  "Oberlin",
  "Kenyon",
  "Reed",
  "Scripps",
  "Pitzer",
  "Mount Holyoke",
  "Bryn Mawr",
  "Barnard",
  "Trinity College (CT)",
  "Connecticut College",
  "Skidmore",
  "Sarah Lawrence",
  "Bard",
  "Wheaton (MA)",
  "Wheaton (IL)",
  "Dickinson",
  "Franklin & Marshall",
  "Gettysburg",
  "Lafayette",
  "Lehigh",
  "Muhlenberg",
  "Allegheny",
  "Whitman",
  "Lewis & Clark",
  "Willamette",
  "Linfield",
  "Pacific University",
  "University of Puget Sound",
  "Occidental",
  "Soka University of America",
  "St. Olaf",
  "Gustavus Adolphus",
  "Beloit",
  "Lawrence",
  "Knox",
  "Wabash",
  "DePauw",
  "Wofford",
  "Furman",
  "Sewanee (University of the South)",
  "Rhodes",
  "Centre",
  "Hendrix",
  "Earlham",
  "Hampshire",
  "Pomona-Pitzer",
  "Pomona College",
  "Berea",
  "St. John's College (Annapolis)",
  "St. John's College (Santa Fe)",
  "Hampden-Sydney",
  "Washington & Lee",
  "Hollins",
  "Sweet Briar",
  "Goucher",
  "Stonehill",
  "Holy Cross",
  "Providence College",
  "Saint Anselm",
  "Manhattanville",
  "Marist",
  "Siena",
  "Saint Michael's",
  "Endicott",
  // ---- Big public R1 / state flagships ----
  "University of Michigan",
  "Michigan State",
  "University of Virginia",
  "Virginia Tech",
  "William & Mary",
  "George Mason",
  "James Madison University",
  "Old Dominion",
  "UNC Chapel Hill",
  "NC State",
  "UNC Charlotte",
  "UNC Greensboro",
  "UNC Wilmington",
  "East Carolina",
  "Appalachian State",
  "Georgia Tech",
  "University of Georgia",
  "Georgia State",
  "Kennesaw State",
  "Mercer University",
  "Emory & Henry",
  "University of Texas at Austin",
  "UT Dallas",
  "UT San Antonio",
  "UT Arlington",
  "UT El Paso",
  "UT Rio Grande Valley",
  "UT Tyler",
  "Texas A&M",
  "Texas A&M Corpus Christi",
  "Texas Tech",
  "University of Houston",
  "University of North Texas",
  "Texas State",
  "Texas Christian University",
  "Trinity University (TX)",
  "Rice",
  "Sam Houston State",
  "Stephen F. Austin",
  "University of Washington",
  "Washington State",
  "Western Washington",
  "Eastern Washington",
  "Central Washington",
  "University of Wisconsin",
  "UW Milwaukee",
  "UW Eau Claire",
  "UW La Crosse",
  "UW Madison",
  "UW Stevens Point",
  "Marquette",
  "University of Illinois Urbana-Champaign",
  "University of Illinois Chicago",
  "Illinois State",
  "Northern Illinois",
  "Southern Illinois Carbondale",
  "Loyola Chicago",
  "DePaul",
  "Northwestern",
  "Purdue",
  "Indiana University Bloomington",
  "Indiana University-Purdue University Indianapolis (IUPUI)",
  "Ball State",
  "Butler",
  "University of Notre Dame",
  "Valparaiso",
  "Rose-Hulman Institute of Technology",
  "Ohio State",
  "Ohio University",
  "Miami University (OH)",
  "Cincinnati",
  "Akron",
  "Bowling Green",
  "Cleveland State",
  "Kent State",
  "Toledo",
  "Wright State",
  "Youngstown State",
  "Xavier University (OH)",
  "Dayton",
  "Penn State",
  "Penn State Erie",
  "Penn State Harrisburg",
  "Pittsburgh",
  "Temple",
  "Drexel",
  "Villanova",
  "Saint Joseph's University",
  "La Salle",
  "Duquesne",
  "Carnegie Mellon",
  "West Chester University",
  "Indiana University of Pennsylvania",
  "University of Florida",
  "Florida State",
  "University of Miami",
  "University of Central Florida (UCF)",
  "Florida International (FIU)",
  "University of South Florida (USF)",
  "Florida Atlantic (FAU)",
  "Florida Gulf Coast",
  "Florida A&M",
  "Stetson",
  "Rollins",
  "Embry-Riddle Aeronautical",
  "Arizona State",
  "University of Arizona",
  "Northern Arizona",
  "Grand Canyon University",
  "Embry-Riddle Prescott",
  "University of Colorado Boulder",
  "Colorado State",
  "University of Denver",
  "UCCS (Colorado Springs)",
  "Colorado School of Mines",
  "University of Northern Colorado",
  "University of Utah",
  "Utah State",
  "Utah Valley University",
  "Weber State",
  "Southern Utah",
  "BYU",
  "BYU Idaho",
  "BYU Hawaii",
  "University of Oregon",
  "Oregon State",
  "Portland State",
  "Pacific University",
  "Lewis & Clark",
  "Willamette",
  "Reed",
  "George Fox",
  "Eastern Oregon",
  "Southern Oregon",
  "Western Oregon",
  "Oregon Institute of Technology",
  "Rutgers",
  "Rutgers Newark",
  "Rutgers Camden",
  "NJIT (New Jersey Institute of Technology)",
  "Stevens Institute of Technology",
  "Princeton",
  "Rowan",
  "Montclair State",
  "The College of New Jersey (TCNJ)",
  "Drew University",
  "Seton Hall",
  "Stockton University",
  "Rider University",
  "Saint Peter's University",
  "Monmouth University",
  "Kean University",
  "William Paterson",
  "University of Maryland",
  "UMBC",
  "University of Maryland Eastern Shore",
  "Towson",
  "Morgan State",
  "Bowie State",
  "Salisbury",
  "Loyola Maryland",
  "Johns Hopkins",
  "Goucher",
  "Hood College",
  "St. Mary's College of Maryland",
  "United States Naval Academy",
  "United States Military Academy (West Point)",
  "United States Air Force Academy",
  "United States Coast Guard Academy",
  "United States Merchant Marine Academy",
  "Virginia Military Institute (VMI)",
  "The Citadel",
  "University of Georgia",
  "Georgia Tech",
  "Georgia State",
  "Mercer",
  "Spelman",
  "Morehouse",
  "Clark Atlanta",
  "Savannah State",
  "Fort Valley State",
  "Albany State (GA)",
  "Georgia Southern",
  "Georgia College",
  "Kennesaw State",
  "Augusta University",
  "University of Tennessee Knoxville",
  "University of Tennessee Chattanooga",
  "University of Tennessee Martin",
  "Tennessee State",
  "Tennessee Tech",
  "Middle Tennessee State",
  "Memphis",
  "Vanderbilt",
  "Belmont",
  "Lipscomb",
  "Trevecca Nazarene",
  "Sewanee",
  "University of Kentucky",
  "University of Louisville",
  "Western Kentucky",
  "Eastern Kentucky",
  "Murray State",
  "Northern Kentucky",
  "Morehead State",
  "Kentucky State",
  "Centre College",
  "Berea College",
  "University of Alabama",
  "Auburn",
  "UAB (Birmingham)",
  "UAH (Huntsville)",
  "Troy University",
  "Jacksonville State",
  "Tuskegee",
  "Alabama A&M",
  "Alabama State",
  "Samford",
  "Birmingham-Southern",
  "Spring Hill",
  "Faulkner",
  "University of South Alabama",
  "University of Mississippi (Ole Miss)",
  "Mississippi State",
  "Jackson State",
  "Alcorn State",
  "Tougaloo",
  "Mississippi Valley State",
  "Belhaven",
  "Millsaps",
  "LSU",
  "Tulane",
  "Loyola New Orleans",
  "Xavier University of Louisiana",
  "Dillard",
  "Southern University",
  "Grambling State",
  "Louisiana Tech",
  "University of Louisiana at Lafayette",
  "University of Louisiana at Monroe",
  "McNeese State",
  "Northwestern State",
  "Southeastern Louisiana",
  "Nicholls State",
  "University of Arkansas",
  "Arkansas State",
  "University of Central Arkansas",
  "Arkansas Tech",
  "Hendrix",
  "Harding",
  "Ouachita Baptist",
  "University of Arkansas at Little Rock",
  "Philander Smith",
  "University of South Carolina",
  "Clemson",
  "College of Charleston",
  "The Citadel",
  "Furman",
  "Wofford",
  "Presbyterian College",
  "Coastal Carolina",
  "Winthrop",
  "Erskine",
  "Newberry",
  "Allen University",
  "Benedict College",
  "Claflin",
  "Voorhees",
  "South Carolina State",
  // ---- Midwest publics ----
  "University of Minnesota",
  "Minnesota State Mankato",
  "Minnesota State Moorhead",
  "St. Cloud State",
  "Winona State",
  "Bemidji State",
  "Carleton",
  "St. Olaf",
  "Macalester",
  "Hamline",
  "Gustavus Adolphus",
  "Concordia (MN)",
  "St. Thomas (MN)",
  "Augsburg",
  "Iowa State",
  "University of Iowa",
  "Northern Iowa",
  "Drake",
  "Grinnell",
  "Coe",
  "Cornell College",
  "Luther",
  "Wartburg",
  "Loras",
  "Simpson",
  "Buena Vista",
  "Central (IA)",
  "University of Nebraska Lincoln",
  "University of Nebraska Omaha",
  "Creighton",
  "Doane",
  "Hastings",
  "Nebraska Wesleyan",
  "University of Nebraska Kearney",
  "Bellevue University",
  "University of Kansas",
  "Kansas State",
  "Wichita State",
  "Pittsburg State",
  "Emporia State",
  "Fort Hays State",
  "Washburn",
  "Friends University",
  "Sterling College",
  "Tabor",
  "University of Missouri",
  "Missouri State",
  "Saint Louis University",
  "Webster",
  "Lindenwood",
  "Truman State",
  "Northwest Missouri State",
  "Southeast Missouri State",
  "Missouri Western",
  "Missouri Southern",
  "Drury",
  "Washington University in St. Louis",
  "Rockhurst",
  // ---- Mountain west ----
  "Montana State",
  "University of Montana",
  "Carroll College",
  "Rocky Mountain College",
  "University of Wyoming",
  "Idaho State",
  "Boise State",
  "University of Idaho",
  "Lewis-Clark State",
  "University of New Mexico",
  "New Mexico State",
  "New Mexico Tech",
  "Eastern New Mexico",
  "Western New Mexico",
  "Northern Arizona",
  // ---- Pacific Northwest small + religious ----
  "Whitworth",
  "Northwest Nazarene",
  "Gonzaga",
  "Whitman",
  "Pacific Lutheran",
  "Seattle Pacific",
  "Walla Walla",
  // ---- New England + NY ----
  "University of Connecticut (UConn)",
  "UConn Stamford",
  "Sacred Heart",
  "Fairfield",
  "Quinnipiac",
  "Yale",
  "Trinity College (CT)",
  "Wesleyan",
  "Connecticut College",
  "Central Connecticut State",
  "Southern Connecticut State",
  "Western Connecticut State",
  "Eastern Connecticut State",
  "University of New Hampshire",
  "Plymouth State",
  "Keene State",
  "Saint Anselm",
  "Dartmouth",
  "Franklin Pierce",
  "Southern New Hampshire University (SNHU)",
  "University of Vermont",
  "Middlebury",
  "Norwich University",
  "Bennington College",
  "Champlain College",
  "Castleton",
  "Saint Michael's",
  "University of Maine",
  "University of Southern Maine",
  "Bates",
  "Bowdoin",
  "Colby",
  "Maine Maritime",
  "University of Massachusetts Amherst",
  "UMass Boston",
  "UMass Lowell",
  "UMass Dartmouth",
  "Boston College",
  "Boston University",
  "Northeastern",
  "Tufts",
  "MIT",
  "Harvard",
  "Wellesley",
  "Smith",
  "Mount Holyoke",
  "Amherst",
  "Williams",
  "Bentley",
  "Babson",
  "Suffolk",
  "Emerson",
  "Brandeis",
  "Worcester State",
  "Worcester Polytechnic Institute (WPI)",
  "Bridgewater State",
  "Salem State",
  "Fitchburg State",
  "Framingham State",
  "Westfield State",
  "Massachusetts Maritime",
  "University of Rhode Island",
  "Brown",
  "Providence College",
  "Rhode Island College",
  "Roger Williams",
  "Salve Regina",
  "Bryant",
  "Stony Brook",
  "Binghamton",
  "Buffalo (SUNY)",
  "Albany (SUNY)",
  "SUNY Geneseo",
  "SUNY New Paltz",
  "SUNY Plattsburgh",
  "SUNY Oswego",
  "SUNY Oneonta",
  "SUNY Brockport",
  "SUNY Cortland",
  "SUNY Fredonia",
  "SUNY Potsdam",
  "SUNY Purchase",
  "SUNY Old Westbury",
  "Stony Brook",
  "CUNY Hunter",
  "CUNY Baruch",
  "CUNY City College",
  "CUNY Brooklyn College",
  "CUNY Queens College",
  "CUNY John Jay",
  "CUNY Lehman",
  "CUNY Staten Island",
  "CUNY New York City College of Technology",
  "Columbia",
  "Barnard",
  "NYU",
  "Fordham",
  "Manhattan College",
  "Pace",
  "Iona",
  "Marymount Manhattan",
  "Cooper Union",
  "Pratt",
  "Rensselaer Polytechnic Institute (RPI)",
  "Clarkson",
  "Skidmore",
  "Hobart and William Smith",
  "Hamilton",
  "Colgate",
  "Cornell",
  "Vassar",
  "Bard",
  "Sarah Lawrence",
  "Syracuse",
  "Le Moyne",
  "Hartwick",
  "Union College (NY)",
  "Saint Bonaventure",
  "Niagara",
  "Canisius",
  "Saint John's University (NY)",
  "LIU Post",
  "Adelphi",
  "Hofstra",
  "Long Island University Brooklyn",
  // ---- HBCUs (selected) ----
  "Howard",
  "Spelman",
  "Morehouse",
  "Hampton",
  "Florida A&M",
  "North Carolina A&T",
  "North Carolina Central",
  "Tennessee State",
  "Tuskegee",
  "Xavier University of Louisiana",
  "Dillard",
  "Fisk",
  "Lincoln University (PA)",
  "Lincoln University (MO)",
  "Cheyney University",
  "Bowie State",
  "Morgan State",
  "Bennett College",
  "Clark Atlanta",
  "Albany State (GA)",
  "Fort Valley State",
  "Savannah State",
  "Texas Southern",
  "Prairie View A&M",
  "Alabama A&M",
  "Alabama State",
  "Jackson State",
  "Alcorn State",
  "Mississippi Valley State",
  "Grambling State",
  "Southern University",
  "Virginia State",
  "Virginia Union",
  "Norfolk State",
  "Hampton",
  "Elizabeth City State",
  "Fayetteville State",
  "Winston-Salem State",
  "Johnson C. Smith",
  "Saint Augustine's",
  "Shaw University",
  "South Carolina State",
  "Claflin",
  "Benedict College",
  "Voorhees",
  "Allen University",
  "Paine College",
  "Philander Smith",
  "Wiley College",
  "Huston-Tillotson",
  "Texas College",
  "Bowie State",
  "Coppin State",
  "University of the District of Columbia",
  // ---- Canada (top frequented by US students) ----
  "University of Toronto",
  "McGill",
  "UBC (University of British Columbia)",
  "University of Waterloo",
  "Western University",
  "Queen's University",
  "McMaster",
  "University of Alberta",
  "Simon Fraser",
  "Concordia (Montreal)",
  "York University",
  "University of Ottawa",
  "Carleton University",
  // ---- International (commonly cited) ----
  "Oxford",
  "Cambridge",
  "Imperial College London",
  "UCL",
  "King's College London",
  "London School of Economics (LSE)",
  "ETH Zurich",
  "EPFL",
  "Sciences Po",
  "Trinity College Dublin",
  "University of Edinburgh",
  "University of St Andrews",
  "University of Sydney",
  "University of Melbourne",
  "University of Hong Kong",
  "NUS (National University of Singapore)",
  "NTU Singapore",
  "Tsinghua",
  "Peking University",
  "Seoul National University",
  "KAIST",
  "Yonsei",
  "Korea University",
  "University of Tokyo",
  "Kyoto University",
  "Technion",
  "Tel Aviv University",
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIT Kanpur",
  "ITAM",
  "Tec de Monterrey",
  "Universidad de los Andes",
];

/**
 * Referral source options for the "where did you hear about us" question.
 * Ordered roughly by expected popularity for student users.
 */
export const REFERRAL_OPTIONS: string[] = [
  "Friend / word of mouth",
  "Instagram",
  "TikTok",
  "Reddit",
  "Twitter / X",
  "LinkedIn",
  "YouTube",
  "Google search",
  "Product Hunt",
  "Flyer on campus",
  "Club / org meeting",
  "Class email",
  "News article",
  "Discord server",
];
